// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Buttons: typeof import('./src/components/Buttons.vue')['default']
    'Bx:bxRedo': typeof import('~icons/bx/bx-redo')['default']
    'Bx:bxsDownload': typeof import('~icons/bx/bxs-download')['default']
    'Bx:bxTrash': typeof import('~icons/bx/bx-trash')['default']
    'Bx:bxUndo': typeof import('~icons/bx/bx-undo')['default']
    BxBxCaretDown: typeof import('~icons/bx/bx-caret-down')['default']
    BxBxCloudDownload: typeof import('~icons/bx/bx-cloud-download')['default']
    BxBxCloudUpload: typeof import('~icons/bx/bx-cloud-upload')['default']
    BxBxHome: typeof import('~icons/bx/bx-home')['default']
    BxBxLeftArrowCircle: typeof import('~icons/bx/bx-left-arrow-circle')['default']
    BxBxMoon: typeof import('~icons/bx/bx-moon')['default']
    BxBxRedo: typeof import('~icons/bx/bx-redo')['default']
    BxBxRefresh: typeof import('~icons/bx/bx-refresh')['default']
    BxBxsCloudUpload: typeof import('~icons/bx/bxs-cloud-upload')['default']
    BxBxShareAlt: typeof import('~icons/bx/bx-share-alt')['default']
    BxBxSun: typeof import('~icons/bx/bx-sun')['default']
    BxBxTrash: typeof import('~icons/bx/bx-trash')['default']
    BxBxUndo: typeof import('~icons/bx/bx-undo')['default']
    DarkSwitch: typeof import('./src/components/DarkSwitch.vue')['default']
    DemoCard: typeof import('./src/components/DemoCard.vue')['default']
    DemoImageUpload: typeof import('./src/components/DemoImageUpload.vue')['default']
    DemoList: typeof import('./src/components/DemoList.vue')['default']
    FlashMessage: typeof import('./src/components/FlashMessage.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageInput: typeof import('./src/components/demo/ImageInput.vue')['default']
    ImagePreview: typeof import('./src/components/demo/ImagePreview.vue')['default']
    ImageShare: typeof import('./src/components/demo/ImageShare.vue')['default']
    IonCloseRound: typeof import('~icons/ion/close-round')['default']
    JamCloseCircleF: typeof import('~icons/jam/close-circle-f')['default']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MdiLoading: typeof import('~icons/mdi/loading')['default']
    MessageButtons: typeof import('./src/components/MessageButtons.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    ResultModel: typeof import('./src/components/demo/ResultModel.vue')['default']
    RoundedFullBtn: typeof import('./src/components/RoundedFullBtn.vue')['default']
    SendBtn: typeof import('./src/components/demo/SendBtn.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    ToggleDark: typeof import('./src/components/ToggleDark.vue')['default']
    ToolButton: typeof import('./src/components/ToolButton.vue')['default']
    VsLanguage: typeof import('~icons/vs/language')['default']
  }
}

export { }
