// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Buttons: typeof import('./src/components/Buttons.vue')['default']
    DarkSwitch: typeof import('./src/components/DarkSwitch.vue')['default']
    DemoCard: typeof import('./src/components/DemoCard.vue')['default']
    FlashMessage: typeof import('./src/components/FlashMessage.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RoundedFullBtn: typeof import('./src/components/RoundedFullBtn.vue')['default']
    ImageInput: typeof import('./src/components/demo/ImageInput.vue')['default']
    ImagePreview: typeof import('./src/components/demo/ImagePreview.vue')['default']
    ImageShare: typeof import('./src/components/demo/ImageShare.vue')['default']
    ResultModel: typeof import('./src/components/demo/ResultModel.vue')['default']
    SendBtn: typeof import('./src/components/demo/SendBtn.vue')['default']
  }
}

export { }
