// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Buttons: typeof import('./src/components/Buttons.vue')['default']
    BxBxCaretDown: typeof import('virtual:vite-icons/bx/bx-caret-down')['default']
    BxBxCloudDownload: typeof import('virtual:vite-icons/bx/bx-cloud-download')['default']
    BxBxCloudUpload: typeof import('virtual:vite-icons/bx/bx-cloud-upload')['default']
    BxBxHome: typeof import('virtual:vite-icons/bx/bx-home')['default']
    BxBxLeftArrowCircle: typeof import('virtual:vite-icons/bx/bx-left-arrow-circle')['default']
    BxBxMoon: typeof import('virtual:vite-icons/bx/bx-moon')['default']
    BxBxRedo: typeof import('virtual:vite-icons/bx/bx-redo')['default']
    BxBxRefresh: typeof import('virtual:vite-icons/bx/bx-refresh')['default']
    BxBxsCloudUpload: typeof import('virtual:vite-icons/bx/bxs-cloud-upload')['default']
    BxBxShareAlt: typeof import('virtual:vite-icons/bx/bx-share-alt')['default']
    BxBxSun: typeof import('virtual:vite-icons/bx/bx-sun')['default']
    BxBxTrash: typeof import('virtual:vite-icons/bx/bx-trash')['default']
    BxBxUndo: typeof import('virtual:vite-icons/bx/bx-undo')['default']
    DarkSwitch: typeof import('./src/components/DarkSwitch.vue')['default']
    DemoCard: typeof import('./src/components/DemoCard.vue')['default']
    DemoImageUpload: typeof import('./src/components/DemoImageUpload.vue')['default']
    FlashMessage: typeof import('./src/components/FlashMessage.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageInput: typeof import('./src/components/demo/ImageInput.vue')['default']
    ImagePreview: typeof import('./src/components/demo/ImagePreview.vue')['default']
    ImageShare: typeof import('./src/components/demo/ImageShare.vue')['default']
    IonCloseRound: typeof import('virtual:vite-icons/ion/close-round')['default']
    JamCloseCircleF: typeof import('virtual:vite-icons/jam/close-circle-f')['default']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MdiLoading: typeof import('virtual:vite-icons/mdi/loading')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    ResultModel: typeof import('./src/components/demo/ResultModel.vue')['default']
    RoundedFullBtn: typeof import('./src/components/RoundedFullBtn.vue')['default']
    SendBtn: typeof import('./src/components/demo/SendBtn.vue')['default']
    VsLanguage: typeof import('virtual:vite-icons/vs/language')['default']
  }
}

export { }
