// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DemoCard: typeof import('./components/DemoCard.vue')['default']
    DemoImageUpload: typeof import('./components/DemoImageUpload.vue')['default']
    DemoList: typeof import('./components/DemoList.vue')['default']
    DynamicForm: typeof import('./components/DynamicForm.vue')['default']
    FlashMessage: typeof import('./components/FlashMessage.vue')['default']
    ImageInput: typeof import('./components/demo/ImageInput.vue')['default']
    ImagePreview: typeof import('./components/demo/ImagePreview.vue')['default']
    ImageShare: typeof import('./components/demo/ImageShare.vue')['default']
    LanguageSelect: typeof import('./components/LanguageSelect.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    LogoutButton: typeof import('./components/LogoutButton.vue')['default']
    MessageButtons: typeof import('./components/MessageButtons.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    ResultModel: typeof import('./components/demo/ResultModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendBtn: typeof import('./components/demo/SendBtn.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    ToggleDark: typeof import('./components/ToggleDark.vue')['default']
    ToolButton: typeof import('./components/ToolButton.vue')['default']
  }
}

export {}
