// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Bx:bxRedo': typeof import('~icons/bx/bx-redo')['default']
    'Bx:bxsDownload': typeof import('~icons/bx/bxs-download')['default']
    'Bx:bxTrash': typeof import('~icons/bx/bx-trash')['default']
    'Bx:bxUndo': typeof import('~icons/bx/bx-undo')['default']
    BxBxCaretDown: typeof import('~icons/bx/bx-caret-down')['default']
    BxBxCloudDownload: typeof import('~icons/bx/bx-cloud-download')['default']
    BxBxCloudUpload: typeof import('~icons/bx/bx-cloud-upload')['default']
    BxBxMoon: typeof import('~icons/bx/bx-moon')['default']
    BxBxRefresh: typeof import('~icons/bx/bx-refresh')['default']
    BxBxsCloudUpload: typeof import('~icons/bx/bxs-cloud-upload')['default']
    BxBxShareAlt: typeof import('~icons/bx/bx-share-alt')['default']
    BxBxSun: typeof import('~icons/bx/bx-sun')['default']
    DemoCard: typeof import('./components/DemoCard.vue')['default']
    DemoImageUpload: typeof import('./components/DemoImageUpload.vue')['default']
    DemoList: typeof import('./components/DemoList.vue')['default']
    DynamicForm: typeof import('./components/DynamicForm.vue')['default']
    'EosIcons:threeDotsLoading': typeof import('~icons/eos-icons/three-dots-loading')['default']
    FlashMessage: typeof import('./components/FlashMessage.vue')['default']
    ImageInput: typeof import('./components/demo/ImageInput.vue')['default']
    ImagePreview: typeof import('./components/demo/ImagePreview.vue')['default']
    ImageShare: typeof import('./components/demo/ImageShare.vue')['default']
    IonCloseRound: typeof import('~icons/ion/close-round')['default']
    JamCloseCircleF: typeof import('~icons/jam/close-circle-f')['default']
    LanguageSelect: typeof import('./components/LanguageSelect.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    LogoutButton: typeof import('./components/LogoutButton.vue')['default']
    MdiLoading: typeof import('~icons/mdi/loading')['default']
    MessageButtons: typeof import('./components/MessageButtons.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    ResultModel: typeof import('./components/demo/ResultModel.vue')['default']
    SendBtn: typeof import('./components/demo/SendBtn.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    ToggleDark: typeof import('./components/ToggleDark.vue')['default']
    ToolButton: typeof import('./components/ToolButton.vue')['default']
    VsLanguage: typeof import('~icons/vs/language')['default']
  }
}

export { }
