name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build Production
        run: npm run build

  deploy-azure-web:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web App - Intel
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build Production
        env:
          VITE_FUNCTIONS_ENDPOINT: https://ovaas-backend.azurewebsites.net/api
        run: npm run build

      - name: Deploy to ASWA
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_ROCK_03BB9DD00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: /
          api_location: .output/server
          output_location: .output/public
          skip_app_build: true

  deploy-azure-web-docker:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web App - Intel (Docker Back-end)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build Production
        env:
          VITE_FUNCTIONS_ENDPOINT: https://ovaas-backend-docker.azurewebsites.net/api
        run: npm run build

      - name: Deploy to ASWA
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_GLACIER_0F2661300 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: /
          api_location: .output/server
          output_location: .output/public
          skip_app_build: true
